# Generated by Django 3.0 on 2019-12-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website_url', models.CharField(default='None', max_length=150)),
                ('stream_url', models.CharField(default='None', max_length=150)),
                ('service_ndj_url', models.CharField(default='None', max_length=150)),
                ('service_ndj_id', models.IntegerField(default=0)),
                ('playlist_sp_url', models.CharField(default='None', max_length=100)),
                ('playlist_yt_url', models.CharField(default='None', max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrobbell.Country')),
            ],
        ),
    ]
