# Generated by Django 3.0 on 2019-12-12 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrobbell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistLast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rds', models.CharField(max_length=150)),
                ('listeners', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrobbell.Station')),
            ],
        ),
    ]
