# Generated by Django 3.0 on 2019-12-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrobbell', '0004_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='clip',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='ds_album',
            field=models.CharField(default='None', max_length=300),
        ),
        migrations.AddField(
            model_name='song',
            name='ds_country',
            field=models.ManyToManyField(to='scrobbell.Country'),
        ),
        migrations.AddField(
            model_name='song',
            name='ds_img',
            field=models.CharField(default='None', max_length=400),
        ),
        migrations.AddField(
            model_name='song',
            name='ds_thm',
            field=models.CharField(default='None', max_length=400),
        ),
        migrations.AddField(
            model_name='song',
            name='ds_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='sp_pop',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='sp_prev',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='sp_uri',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='song',
            name='ds_genre',
            field=models.ManyToManyField(to='scrobbell.Genre'),
        ),
        migrations.AddField(
            model_name='song',
            name='ds_label',
            field=models.ManyToManyField(to='scrobbell.Label'),
        ),
        migrations.AddField(
            model_name='song',
            name='ds_style',
            field=models.ManyToManyField(to='scrobbell.Style'),
        ),
    ]
