# Generated by Django 3.0 on 2019-12-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrobbell', '0005_auto_20191212_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='ds_country',
            field=models.ManyToManyField(to='scrobbell.Country', verbose_name='countries'),
        ),
        migrations.AlterField(
            model_name='song',
            name='ds_genre',
            field=models.ManyToManyField(to='scrobbell.Genre', verbose_name='genres'),
        ),
        migrations.AlterField(
            model_name='song',
            name='ds_label',
            field=models.ManyToManyField(to='scrobbell.Label', verbose_name='labels'),
        ),
        migrations.AlterField(
            model_name='song',
            name='ds_style',
            field=models.ManyToManyField(to='scrobbell.Style', verbose_name='styles'),
        ),
    ]
