# Generated by Django 3.0 on 2019-12-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrobbell', '0006_auto_20191212_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='sp_uri',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
