# Generated by Django 3.0 on 2019-12-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrobbell', '0008_song_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='total_plays',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
