# Generated by Django 3.0 on 2019-12-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrobbell', '0009_song_total_plays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='station',
            name='img',
            field=models.ImageField(blank=True, upload_to='uploads/', width_field=200),
        ),
    ]
