# Generated by Django 3.0 on 2019-12-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrobbell', '0010_auto_20191225_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='height',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='width',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
