# Generated by Django 3.0 on 2019-12-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrobbell', '0012_auto_20191225_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='img',
            field=models.ImageField(blank=True, height_field='height', upload_to='stations/', width_field='width'),
        ),
    ]
