# Generated by Django 3.0 on 2019-12-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrobbell', '0014_station_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='station',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
