# Generated by Django 3.0.3 on 2020-03-05 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrobbell', '0016_auto_20200305_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
